{
    "name": "C2P Property & Lease Management",
    "version": "19.0.1.0.0",
    "category": "Services/Real Estate",
    "summary": "Buildings, units, tenancy leases, PDC register and landlord statements for UAE property management",
    "author": "C2P Consultants",
    "website": "https://www.core2plus.com",
    "license": "OPL-1",
    "depends": [
        "base",
        "mail",
        "account",
        "sale_subscription",
        "analytic",
        "contacts",
    ],
    "data": [
        "security/c2p_security.xml",
        "security/ir.model.access.csv",
        "data/product_data.xml",
        "data/ir_sequence.xml",
        "data/ir_cron.xml",
        "report/owner_statement_report.xml",
        "views/building_views.xml",
        "views/unit_views.xml",
        "views/lease_views.xml",
        "views/account_payment_views.xml",
        "wizard/pdc_register_views.xml",
        "wizard/lease_renew_views.xml",
        "wizard/lease_terminate_views.xml",
        "wizard/owner_statement_views.xml",
        "views/menus.xml",
    ],
    "application": True,
    "installable": True,
}
